"""Type stubs for the Rust extension module."""

from typing import Optional, List, Tuple

# Data Models

class Agency:
    """A transit agency."""

    def __init__(
        self,
        name: str,
        url: str,
        timezone: str,
        id: Optional[str] = None,
    ) -> None: ...

    @property
    def id(self) -> Optional[str]: ...
    @property
    def name(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def timezone(self) -> str: ...

class Stop:
    """A transit stop."""

    def __init__(
        self,
        id: str,
        name: str,
        latitude: float,
        longitude: float,
    ) -> None: ...

    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def latitude(self) -> float: ...
    @property
    def longitude(self) -> float: ...
    @property
    def code(self) -> Optional[str]: ...

class Route:
    """A transit route."""

    @property
    def id(self) -> str: ...
    @property
    def short_name(self) -> Optional[str]: ...
    @property
    def long_name(self) -> Optional[str]: ...
    @property
    def route_type(self) -> int: ...

class Trip:
    """A transit trip."""

    @property
    def id(self) -> str: ...
    @property
    def route_id(self) -> str: ...
    @property
    def service_id(self) -> str: ...
    @property
    def headsign(self) -> Optional[str]: ...

class StopTime:
    """A stop time within a trip."""

    @property
    def trip_id(self) -> str: ...
    @property
    def stop_id(self) -> str: ...
    @property
    def stop_sequence(self) -> int: ...
    @property
    def arrival_time(self) -> Optional[str]: ...
    @property
    def departure_time(self) -> Optional[str]: ...

class Calendar:
    """A service calendar."""

    @property
    def service_id(self) -> str: ...
    @property
    def monday(self) -> bool: ...
    @property
    def tuesday(self) -> bool: ...
    @property
    def wednesday(self) -> bool: ...
    @property
    def thursday(self) -> bool: ...
    @property
    def friday(self) -> bool: ...
    @property
    def saturday(self) -> bool: ...
    @property
    def sunday(self) -> bool: ...
    @property
    def start_date(self) -> str: ...
    @property
    def end_date(self) -> str: ...

class CalendarDate:
    """A calendar exception date."""

    @property
    def service_id(self) -> str: ...
    @property
    def date(self) -> str: ...
    @property
    def exception_type(self) -> int: ...

class Shape:
    """A route shape."""

    @property
    def id(self) -> str: ...
    @property
    def points(self) -> List[Tuple[float, float, int]]: ...

# GTFS

class GtfsFeed:
    """A GTFS feed."""

    def __init__(self) -> None: ...

    @staticmethod
    def from_path(path: str) -> "GtfsFeed": ...

    @staticmethod
    def from_zip(path: str) -> "GtfsFeed": ...

    @staticmethod
    def from_bytes(data: bytes) -> "GtfsFeed": ...

    def to_path(self, path: str) -> None: ...
    def to_zip(self, path: str) -> None: ...
    def to_bytes(self) -> bytes: ...

    @property
    def agencies(self) -> List[Agency]: ...
    @property
    def stops(self) -> List[Stop]: ...
    @property
    def routes(self) -> List[Route]: ...
    @property
    def trips(self) -> List[Trip]: ...
    @property
    def stop_times(self) -> List[StopTime]: ...
    @property
    def calendars(self) -> List[Calendar]: ...
    @property
    def calendar_dates(self) -> List[CalendarDate]: ...
    @property
    def shapes(self) -> List[Shape]: ...

    @property
    def agency_count(self) -> int: ...
    @property
    def stop_count(self) -> int: ...
    @property
    def route_count(self) -> int: ...
    @property
    def trip_count(self) -> int: ...
    @property
    def stop_time_count(self) -> int: ...
    @property
    def calendar_count(self) -> int: ...
    @property
    def calendar_date_count(self) -> int: ...
    @property
    def shape_count(self) -> int: ...


class LazyGtfsFeed:
    """A lazily-loaded GTFS feed.

    This class defers CSV parsing until properties are first accessed,
    providing faster initial load times for large feeds.
    """

    def __init__(self) -> None: ...

    @staticmethod
    def from_path(path: str) -> "LazyGtfsFeed":
        """Load a GTFS feed lazily from a directory path."""
        ...

    @staticmethod
    def from_zip(path: str) -> "LazyGtfsFeed":
        """Load a GTFS feed lazily from a ZIP file."""
        ...

    @staticmethod
    def from_bytes(data: bytes) -> "LazyGtfsFeed":
        """Load a GTFS feed lazily from ZIP bytes."""
        ...

    def materialize(self) -> GtfsFeed:
        """Convert to a regular GtfsFeed with all data loaded."""
        ...

    @property
    def agencies(self) -> List[Agency]: ...
    @property
    def stops(self) -> List[Stop]: ...
    @property
    def routes(self) -> List[Route]: ...
    @property
    def trips(self) -> List[Trip]: ...
    @property
    def stop_times(self) -> List[StopTime]: ...
    @property
    def calendars(self) -> List[Calendar]: ...
    @property
    def calendar_dates(self) -> List[CalendarDate]: ...
    @property
    def shapes(self) -> List[Shape]: ...

    @property
    def agency_count(self) -> int: ...
    @property
    def stop_count(self) -> int: ...
    @property
    def route_count(self) -> int: ...
    @property
    def trip_count(self) -> int: ...
    @property
    def stop_time_count(self) -> int: ...
    @property
    def calendar_count(self) -> int: ...
    @property
    def calendar_date_count(self) -> int: ...
    @property
    def shape_count(self) -> int: ...


# TXC

class TxcDocument:
    """A TransXChange document."""

    @staticmethod
    def from_path(path: str) -> "TxcDocument": ...

    @staticmethod
    def from_bytes(data: bytes) -> "TxcDocument": ...

    @staticmethod
    def from_string(xml: str) -> "TxcDocument": ...

    @property
    def schema_version(self) -> str: ...
    @property
    def filename(self) -> Optional[str]: ...
    @property
    def operator_count(self) -> int: ...
    @property
    def service_count(self) -> int: ...
    @property
    def stop_point_count(self) -> int: ...
    @property
    def vehicle_journey_count(self) -> int: ...
    @property
    def journey_pattern_section_count(self) -> int: ...

    def get_operator_names(self) -> List[str]: ...
    def get_service_codes(self) -> List[str]: ...
    def get_stop_codes(self) -> List[str]: ...

# CSV

class CsvDocument:
    """A CSV document."""

    def __init__(self) -> None: ...

    @staticmethod
    def from_path(path: str) -> "CsvDocument": ...

    @staticmethod
    def from_bytes(data: bytes) -> "CsvDocument": ...

    @staticmethod
    def from_string(csv: str) -> "CsvDocument": ...

    def to_path(self, path: str) -> None: ...
    def to_string(self) -> str: ...

    def __len__(self) -> int: ...

    @property
    def columns(self) -> List[str]: ...
    @property
    def rows(self) -> List[dict]: ...

# JSON

class JsonDocument:
    """A JSON document."""

    @staticmethod
    def from_path(path: str) -> "JsonDocument": ...

    @staticmethod
    def from_bytes(data: bytes) -> "JsonDocument": ...

    @staticmethod
    def from_string(json: str) -> "JsonDocument": ...

    def to_path(self, path: str) -> None: ...
    def to_string(self) -> str: ...
    def to_string_pretty(self) -> str: ...

    def is_object(self) -> bool: ...
    def is_array(self) -> bool: ...

    @property
    def root(self) -> object: ...

    def pointer(self, path: str) -> Optional[object]: ...

# Adapters

class ConversionOptions:
    """Options for TXC to GTFS conversion."""

    def __init__(
        self,
        include_shapes: bool = False,
        calendar_start: Optional[str] = None,
        calendar_end: Optional[str] = None,
        region: str = "england",
        default_timezone: str = "Europe/London",
        default_agency_url: str = "https://example.com",
    ) -> None: ...

    @property
    def include_shapes(self) -> bool: ...

class ConversionStats:
    """Statistics from conversion."""

    @property
    def agencies_converted(self) -> int: ...
    @property
    def stops_converted(self) -> int: ...
    @property
    def routes_converted(self) -> int: ...
    @property
    def trips_converted(self) -> int: ...
    @property
    def stop_times_generated(self) -> int: ...
    @property
    def calendar_entries(self) -> int: ...
    @property
    def calendar_exceptions(self) -> int: ...
    @property
    def shapes_generated(self) -> int: ...

class ConversionResult:
    """Result of TXC to GTFS conversion."""

    @property
    def feed(self) -> GtfsFeed: ...
    @property
    def warnings(self) -> List[str]: ...
    @property
    def stats(self) -> ConversionStats: ...

class TxcToGtfsConverter:
    """TXC to GTFS converter."""

    def __init__(self, options: Optional[ConversionOptions] = None) -> None: ...

    def convert(self, document: TxcDocument) -> ConversionResult: ...
    def convert_batch(self, documents: List[TxcDocument]) -> ConversionResult: ...
